citation-styles/acm-sig-proceedings.csl
citation-styles/acs-nano.csl
citation-styles/apa.csl
citation-styles/associacao-brasileira-de-normas-tecnicas.csl
citation-styles/bibtex.csl
citation-styles/chicago-author-date.csl
citation-styles/harvard-cite-them-right.csl
citation-styles/ieee.csl
citation-styles/modern-language-association.csl
citation-styles/turabian-fullnote-bibliography.csl
citation-styles/vancouver.csl

Newest version of CSL files from
https://github.com/citation-style-language/styles/commit/4268d58146d198a75ceec5e5185bdc08ceffa69e
This includes CMOS 17th edition and MLA 8th edition.

Update CSL styles

---

CitationStyleLanguageSettingsForm.inc.php

Updates the SelectListPanel data to match the new way of handling selected
items for the select all feature.

pkp/pkp-lib#2102 Fix selected items in settings form.

---

locale/es_ES/locale.xml

Each plugin needs, at least, a title and a description. Otherwise, plugins' list will look wired.

Needs a title and a description

---

locale/fi_FI/locale.xml

Add support for Finnish

---

CitationStyleLanguagePlugin.inc.php

s. https://github.com/pkp/pkp-lib/issues/3394
The CSL only supports one Serbian sr-SR, s. https://github.com/citation-style-language/locales

pkp/pkp-lib#3394 consider only sr-RS CSL locale

---

CitationStyleLanguagePlugin.inc.php
CitationStyleLanguageSettingsForm.inc.php

This addresses pkp/pkp-lib#3578 for this plugin.

pkp/pkp-lib#3578: auditing initData() usage

---

CitationStyleLanguagePlugin.inc.php

s. https://github.com/pkp/pkp-lib/issues/2958

given and family name

---

locale/es_ES/locale.xml

received from @marcbria by email

es_ES locale update

---

locale/tr_TR/locale.xml

* this is for pkp/pkp-lib#4005

tr_TR locale added

---

CitationStyleLanguageSettingsForm.inc.php

Plugin follow-up from pkp/pkp-lib#3578.

---

locale/sl_SI/locale.xml

@mtub  Continuing with the Slovenian localization....

Lokalization to Slovenian, OJS 3.1.1.2

---

templates/citation-styles/ris.tpl

See https://github.com/pkp/pkp-lib/issues/4448
This should be cherry-picked to stable branches.

pkp/pkp-lib#4448 Fix RIS template format

---

pages/CitationStyleLanguageHandler.inc.php

s. https://github.com/pkp/pkp-lib/issues/4340

pkp/pkp-lib#4340 fix getting the contextId

---

locale/fr_CA/locale.xml

(Among others : adding publisher place to comply with
https://github.com/pkp/pkp-lib/issues/4946)

Revision and update for fr_CA translation

---

composer.lock
locale/bg_BG/locale.po

Adding Bulgarian locale

---

CitationStyleLanguagePlugin.php

See [https://github.com/pkp/omp/pull/1245#discussion_r1100876811](https://github.com/pkp/omp/pull/1245#discussion_r1100876811)

Use new function getChapterBySourceChapterId

---

CitationStyleLanguagePlugin.php

Ref: https://github.com/pkp/pkp-lib/issues/699

pkp/pkp-lib#699 Show locale in url in multilingual contexts

---

CitationStyleLanguagePlugin.php

pkp/pkp-lib#10292 Controlled vocab dao to eloquent model

---

CitationStyleLanguagePlugin.php
composer.json
composer.lock

pkp/pkp-lib#10973 PHP 8.2 upgrade

---

CitationStyleLanguagePlugin.php
pages/CitationStyleLanguageHandler.php

for pkp/citationStyleLanguage#143

pkp/citationStyleLanguage#143 Fixed OPS compatibility and published submission checking

---

CitationStyleLanguagePlugin.php

[https://github.com/pkp/pkp-lib/issues/10154](https://github.com/pkp/pkp-lib/issues/10154)

fix for issue #10154
